### ISSUE TITLE
error on opening document

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#1387] opened 2020-02-10 17:45 UTC
When user uploads data documents for a new CO group and tries to open the documents, instead of seeing the document user sees a '403 Forbidden' error message.

http://factotum.epa.gov/media/21490e9f-2816-4344-bce3-b4fbffd5ca2d/pdf/document_1511824.pdf

Definition of Done:
User is able to open documents after uploading them to a new data group without seeing an error.

**Comment by michael-barbour** [comment] 2020-02-20 17:29
I'm going to add a blocker of #1388

It seems like the crux of this issue comes down to Django writing into directories with the default permission of 644 and not giving the directories execute permissions.  This means when nginx attempts to navigate through these directories it fails due to a permission issue.

To replicate this bug on dev:
- Docker-compose up with a prod build (replace override.dev with override in the compose files)
- Match a data document with a file on the data group page. e.g. data group 18 (thanks Zach)
- Load the document's file on the document detail page.  Take note of the UUID
- Change the media/{uuid}/pdf directory permissions to exclude execute `sudo chmod 664 path/to/pdf`
- *Clear your browser cache* and reload the document.

Here are the `.env` commands I run followed by the `.env` variables I set.  Obviously these will change based on database name and where your `MEDIA_MOUNT` is
> SQL_DATABASE=factotum_prod SQL_HOST=127.0.0.1 mng migrate
> SQL_DATABASE=factotum_prod SQL_HOST=127.0.0.1 mng migrate --fake elastic 0003
> SQL_DATABASE=factotum_prod SQL_HOST=127.0.0.1 mng migrate elastic
> docker-compose build
> docker-compose down
> docker volume rm docker_factotumstatic 
> docker-compose up -d     
> 
> COMPOSE_PATH_SEPARATOR=;
> COMPOSE_FILE=docker/docker-compose.yaml;docker/docker-compose.override.yaml;docker/docker-compose.mysql.override.yaml
> ALLOWED_HOSTS=*
> ES_MEMORY_LIMIT=1g
> FACTOTUM_SECRET_KEY=test
> FACTOTUM_BRANCH=dev
> FACTOTUM_WS_BRANCH=dev
> FACTOTUM_WS_SECRET_KEY=test
> LS_MEMORY_LIMIT=1g
> MEDIA_MOUNT=/home/michael/Code/factotum/media
> QUERY_LOG_DATABASE=factotum
> REINDEX_SCHEDULE=*/30 1 * * * America/New_York
> SQL_DATABASE=factotum
> SQL_HOST=mysql
> SQL_PASSWORD=factotum
> SQL_USER=root

**Comment by michael-barbour** [comment] 2020-02-27 21:06
Tested again post #1366's merge to dev.  Could not reproduce.

**Comment by michael-barbour** [comment] 2020-02-27 21:32
Closing per Dave's request.  If this problem continues please reopen the ticket.

**Closed by michael-barbour** 2020-02-27 21:32 UTC
Labels: bug, hot fix
