### ISSUE TITLE
display curated chemical information on data document page

### ISSUE THREAD

**Issue by kdionisio** [HumanExposure/factotum#483] opened 2018-10-17 21:04 UTC
On the Data document view page (http://factotum.epa.gov/datadocument/254864/), the user can currently view the extracted chemical information. User would also like to view the associated curated chemical information.

Definition of Done:
On the data document view page, user sees the following fields from the dsstoxsubstance model alongside the appropriate entry for extracted chemical
  - true_cas
  - true_chemname
  - sid

**Comment by debboutr** [comment] 2018-10-24 05:40
this is a duplicate of #444

**Closed** 2018-10-24 13:19 UTC
